-- =====================================================
-- ClinicFlow Database Setup
-- Oracle XE (Docker)
-- Pluggable Database: XEPDB1
-- Schema: CLINIC_FLOW_DB
-- =====================================================

--------------------------------------------------------
-- Connect as SYSDBA and switch to XEPDB1
--------------------------------------------------------

ALTER SESSION SET CONTAINER = XEPDB1;

--------------------------------------------------------
-- Create application schema
--------------------------------------------------------

CREATE USER clinic_flow_db IDENTIFIED BY clinic123;

GRANT CREATE SESSION TO clinic_flow_db;
GRANT RESOURCE TO clinic_flow_db;
ALTER USER clinic_flow_db QUOTA UNLIMITED ON USERS;

--------------------------------------------------------
-- Connect as application user
--------------------------------------------------------

CONNECT clinic_flow_db/clinic123@XEPDB1;

--------------------------------------------------------
-- USERS
--------------------------------------------------------

CREATE TABLE USERS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL
);

--------------------------------------------------------
-- PATIENTS
--------------------------------------------------------

CREATE TABLE PATIENTS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FULL_NAME VARCHAR2(150) NOT NULL,
    DOB DATE NOT NULL,
    EMAIL VARCHAR2(150),
    PHONE_NUMBER VARCHAR2(20)
);

--------------------------------------------------------
-- ALLERGIES
--------------------------------------------------------

CREATE TABLE ALLERGIES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ALLERGY_TYPE VARCHAR2(100) NOT NULL
);

--------------------------------------------------------
-- CLINICS
--------------------------------------------------------

CREATE TABLE CLINICS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(150) NOT NULL,
    LOCATION VARCHAR2(255) NOT NULL
);

--------------------------------------------------------
-- PROVIDERS
--------------------------------------------------------

CREATE TABLE PROVIDERS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(150) NOT NULL,
    SPECIALITY VARCHAR2(100) NOT NULL,
    CLINIC_ID NUMBER NOT NULL,
    CONSTRAINT FK_PROVIDER_CLINIC
        FOREIGN KEY (CLINIC_ID)
        REFERENCES CLINICS(ID)
);

--------------------------------------------------------
-- APPOINTMENTS
--------------------------------------------------------

CREATE TABLE APPOINTMENTS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PATIENT_ID NUMBER NOT NULL,
    CLINIC_ID NUMBER NOT NULL,
    PROVIDER_ID NUMBER NOT NULL,
    APPOINTMENT_DATETIME TIMESTAMP NOT NULL,
    REASON_FOR_VISIT VARCHAR2(255),

    CONSTRAINT FK_APPOINTMENT_PATIENT
        FOREIGN KEY (PATIENT_ID)
        REFERENCES PATIENTS(ID),

    CONSTRAINT FK_APPOINTMENT_CLINIC
        FOREIGN KEY (CLINIC_ID)
        REFERENCES CLINICS(ID),

    CONSTRAINT FK_APPOINTMENT_PROVIDER
        FOREIGN KEY (PROVIDER_ID)
        REFERENCES PROVIDERS(ID)
);

--------------------------------------------------------
-- PATIENT_ALLERGIES
--------------------------------------------------------

CREATE TABLE PATIENT_ALLERGIES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PATIENT_ID NUMBER NOT NULL,
    ALLERGY_ID NUMBER NOT NULL,
    SEVERITY VARCHAR2(20) NOT NULL,
    NOTES VARCHAR2(255),

    CONSTRAINT FK_PATIENT_ALLERGY_PATIENT
        FOREIGN KEY (PATIENT_ID)
        REFERENCES PATIENTS(ID),

    CONSTRAINT FK_PATIENT_ALLERGY_ALLERGY
        FOREIGN KEY (ALLERGY_ID)
        REFERENCES ALLERGIES(ID)
);

COMMIT;